source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'faye-websocket', '~> 0.11'
gem 'puma', '~> 6.0'
gem 'json'

group :test do
  gem 'rack-test'
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'websocket-client-simple'
end
